---
title: "Flex Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
data("nyc_airbnb")

nyc_airbnb =
  nyc_airbnb |>
  mutate(stars = review_scores_location/2) |>
  select(borough = neighbourhood_group, neighbourhood, stars, price, room_type, lat, long) |>
  drop_na(stars) |>
  filter(
    borough == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500
  )
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
nyc_airbnb |>
  mutate(text_label = str_c("Price: $", price, "\nRating: ", stars)) |>
  plot_ly(
    x = ~lat, y = ~long, color = ~price, text = ~text_label,
    type = "scatter", mode = "markers", alpha = 0.5)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

